### ISSUE TITLE
headers download when minority forked

### ISSUE THREAD

**Issue by gandrewstone** [ftrader-bitcoinunlimited/BitcoinUnlimited#8]
In a persistent network minority fork, block headers are not downloaded from minority fork following nodes because the headers from the majority fork are longer.  So a minority fork following node cannot sync.

There is a test case that shows this problem in invalidateblock.py "def testChainSyncWithLongerInvalid(self)".
The test is not currently failing because the failure case does not assert().

This, or a similar problem, is also causing a node to not sync post-fork.  See buip055.py "Test that the forked nodes accept this block as the fork block".

**Comment by sickpig** [comment]
@gandrewstone 

project bitcoin abc (core 0.14.1 - segwit - rbf + EC) forked bitcoin core testnet multiple times, all the forks were backed by a minority part of the hash rate, and the headers  problem never raised. 

Wonder if the bugs was present in 0.12 Core code base and has fixed this bug in 0.13/0.14. So that BU inherited the bug but not the fix.

**Comment by gandrewstone** [comment]
fixed
